# Generated by Django 4.0 on 2024-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='file',
            field=models.FileField(upload_to='core/files/'),
        ),
    ]
