# Generated by Django 4.0 on 2024-04-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_company_code_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vendor_code',
            field=models.CharField(default=str, max_length=19, unique=True),
            preserve_default=False,
        ),
    ]
