# Generated by Django 4.0 on 2024-04-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_vendor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=19, null=True, unique=True),
        ),
    ]
